### PR TITLE
Improve efficiency of salt functions

### PR DESCRIPTION
**Pull request by kkirsche**
This improves the efficiency of salt functions by reducing the number of times calculations need to occur (setting a single variable holding values used multiple times) and reduces the decision tree by using `switch` statements instead of `if` or `if else` statements.

### CODE REVIEW

**Comment by kless** [comment]
Im' sure if there is such improvement. Any benchmark?

**Comment by kkirsche** [comment]
I'd recommend revisiting this, but to each their own

**Comment by tredoe** [comment]
Ok @kkirsche , I'll try to review it this weekend.

**Comment by tredoe** [comment]
I've built a benchmark and there is not a clear winner so I'm not going to change the code.

'salt.go':
``` 
func (s *Salt) Generate2(length int) []byte {
	switch {
	case length > s.SaltLenMax:
		length = s.SaltLenMax
	case length < s.SaltLenMin:
		length = s.SaltLenMin
	default:
	}

	saltLen := (length * 6 / 8)
	if (length*6)%8 != 0 {
		saltLen += 1
	}
	salt := make([]byte, saltLen)
	rand.Read(salt)

	magicPrefixLen := len(s.MagicPrefix)
	out := make([]byte, magicPrefixLen+length)
	copy(out, s.MagicPrefix)
	copy(out[magicPrefixLen:], Base64_24Bit(salt))
	return out
}

func (s *Salt) GenerateWRounds2(length, rounds int) []byte {
	switch {
	case length > s.SaltLenMax:
		length = s.SaltLenMax
	case length < s.SaltLenMin:
		length = s.SaltLenMin
	default:
	}

	switch {
	case rounds > s.RoundsMax:
		rounds = s.RoundsMax
	case rounds < s.RoundsMin:
		rounds = s.RoundsMin
	default:
		rounds = s.RoundsDefault
	}

	saltLen := (length * 6 / 8)
	if (length*6)%8 != 0 {
		saltLen += 1
	}
	salt := make([]byte, saltLen)
	rand.Read(salt)

	roundsText := ""
	if rounds != s.RoundsDefault {
		roundsText = "rounds=" + strconv.Itoa(rounds)
	}

	magicPrefixLen := len(s.MagicPrefix)
	roundsTextLen := len(roundsText)
	out := make([]byte, magicPrefixLen+roundsTextLen+length)
	copy(out, s.MagicPrefix)
	copy(out[magicPrefixLen:], []byte(roundsText))
	copy(out[magicPrefixLen+roundsTextLen:], Base64_24Bit(salt))
	return out
}
```
 'salt_test.go':
```
func BenchmarkGenSalt(b *testing.B) {
	for n := 0; n < b.N; n++ {
		_Salt.Generate(8)
	}
}

func BenchmarkGenSalt2(b *testing.B) {
	for n := 0; n < b.N; n++ {
		_Salt.Generate2(8)
	}
}

func BenchmarkGenSaltWRounds(b *testing.B) {
	for n := 0; n < b.N; n++ {
		_Salt.GenerateWRounds(8, 100)
	}
}

func BenchmarkGenSaltWRounds2(b *testing.B) {
	for n := 0; n < b.N; n++ {
		_Salt.GenerateWRounds2(8, 100)
	}
}

```

Run the benchmark:
```
go test -bench=. ./user/crypt/common/
```

**Pull request closed without merging**
